project:
  type: website
  output-dir: ../docs

website:
  title: "Fear alone influences the behaviour of a keystone native prey by an invader; a non-consumptive effect of the catfish invasion of New Zealand’s freshwaters"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    toc: true
    number-sections: true

execute:
  freeze: auto
  warning: false
  message: false